#!/usr/bin/env python3
"""Generate this machine's installed-mechanisms report into `installed/<HOST>.md`.

WHY THIS IS GENERATED
---------------------
`mechanisms/` is a catalogue, not a runtime — entries are installed case by case. That leaves
an obvious hole, stated in `mechanisms/README.md` before this script existed: **a file being
present in the catalogue is not evidence the failure it addresses is handled on your box.**

Brad, 2026-07-22: *"every conductor should have a log in the repo stating what it's using, what
it's not using, how those things are implemented, and where its files live."*

Written by hand, that log is a doc that drifts the moment anyone edits a config — the same decay
that produced a hand-maintained status page and a hand-maintained TODO summary that was wrong
three times. So the mechanical half is READ FROM THE LIVE CONFIG on every run: which hooks are
wired, to which event, pointing at which file, and whether that file actually exists. A wired
hook whose file is missing is the interesting case and it shows up here as MISSING, loudly.

The half that cannot be derived — *why* something was declined, or how a non-standard install
works — is preserved verbatim across regenerations from the existing file, so regenerating never
destroys judgement. Any `## ` section not owned by this script is carried through untouched.

USAGE
    python tools/report-installed.py            # write installed/<HOST>.md
    python tools/report-installed.py --check    # exit 1 if the file is stale (for CI/pre-commit)
"""
from __future__ import annotations

import argparse
import json
import os
import platform
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CLAUDE = Path.home() / ".claude"
SETTINGS = [CLAUDE / "settings.json", CLAUDE / "settings.local.json"]
CATALOGUE = REPO / "mechanisms" / "hooks"

# Sections this script owns and rewrites. Everything else in the file is preserved.
GENERATED = ("Wired hooks (read from the live config)", "Catalogue coverage")
HOST = platform.node().upper()
OUT = REPO / "installed" / f"{HOST}.md"

HOOK_PATH_RE = re.compile(r"[\w./\\~-]*hooks[/\\]([\w.-]+\.py)")


def wired_hooks() -> tuple[list[dict], list[str]]:
    """[{event, file, exists, source}] plus any notes about unreadable config."""
    rows, notes = [], []
    for cfg in SETTINGS:
        if not cfg.exists():
            continue
        try:
            data = json.loads(cfg.read_text(encoding="utf-8"))
        except Exception as exc:
            notes.append(f"{cfg.name}: UNREADABLE ({exc}) — its hooks are NOT represented below")
            continue
        for event, groups in (data.get("hooks") or {}).items():
            for group in groups or []:
                matcher = group.get("matcher")
                for h in group.get("hooks") or []:
                    cmd = h.get("command", "")
                    m = HOOK_PATH_RE.search(cmd)
                    name = m.group(1) if m else "(not a ~/.claude/hooks script)"
                    path = CLAUDE / "hooks" / name if m else None
                    rows.append({
                        "event": event,
                        "matcher": matcher or "*",
                        "file": name,
                        "exists": bool(path and path.exists()),
                        "source": cfg.name,
                        "status": h.get("statusMessage", ""),
                    })
    return rows, notes


_EVENTS = ("SessionStart", "PreToolUse", "PostToolUse", "Stop", "SubagentStop",
           "UserPromptSubmit", "PreCompact", "Notification", "SessionEnd")


def classify(path: Path) -> str:
    """event hook | test | library/CLI.

    Without this, the coverage table read "not wired" for `hook_log.py` (a logging library
    imported BY the hooks) and `hook_rollup.py` (a CLI you run by hand) — both correct as raw
    facts and both actively misleading, since neither is something you wire to an event. A
    table that reports a library as an unadopted control is a tool capable of a misleading
    report, which is the one thing this repo's own lessons say not to build.
    """
    if path.name.endswith("_test.py"):
        return "test"
    try:
        head = "".join(path.read_text(encoding="utf-8", errors="replace").splitlines(True)[:60])
    except Exception:
        return "library/CLI"
    return "event hook" if any(e in head for e in _EVENTS) else "library/CLI"


def render(rows: list[dict], notes: list[str], preserved: str) -> str:
    out = [
        f"# Installed mechanisms — `{HOST}`",
        "",
        "<!-- The 'Wired hooks' and 'Catalogue coverage' sections are GENERATED by",
        "     tools/report-installed.py from this machine's live config. Do not hand-edit them.",
        "     Every other section is preserved verbatim across regenerations — put judgement,",
        "     declined items and non-standard install notes there. -->",
        "",
        "`mechanisms/` is a catalogue, not a runtime. This file is the record of what is actually",
        "**in force on this machine** — so nobody has to infer it from the catalogue's contents.",
        "",
        f"## {GENERATED[0]}",
        "",
    ]
    if notes:
        for n in notes:
            out.append(f"> ⚠️ {n}")
        out.append("")
    if not rows:
        out.append("**No hooks wired.** Either none are installed, or the config could not be read —")
        out.append("see any warning above. An empty table here is NOT evidence of a clean machine.")
    else:
        out.append("| Event | Matcher | Hook file | File present? | Config |")
        out.append("|---|---|---|---|---|")
        for r in sorted(rows, key=lambda r: (r["event"], r["file"])):
            present = "yes" if r["exists"] else "**MISSING — WIRED BUT ABSENT**"
            out.append(f"| `{r['event']}` | `{r['matcher']}` | `{r['file']}` | {present} | `{r['source']}` |")
    out.append("")
    out.append(f"## {GENERATED[1]}")
    out.append("")
    out.append("Which catalogue entries are wired here. **Not-wired is a legitimate choice** — record")
    out.append("the reason in a section below, since this table can only report the fact, not the why.")
    out.append("")
    wired_files = {r["file"] for r in rows}
    if not CATALOGUE.exists():
        out.append(f"> ⚠️ catalogue dir `{CATALOGUE}` not found — coverage unknown, not empty.")
    else:
        out.append("| Catalogue entry | Kind | Wired to an event here? |")
        out.append("|---|---|---|")
        for p in sorted(CATALOGUE.glob("*.py"), key=lambda p: p.name):
            kind = classify(p)
            if kind != "event hook":
                mark = "n/a"
            else:
                mark = "yes" if p.name in wired_files else "**no**"
            out.append(f"| `mechanisms/hooks/{p.name}` | {kind} | {mark} |")
    out.append("")
    if preserved.strip():
        out.append(preserved.strip())
        out.append("")
    else:
        out.append("## Declined, and why")
        out.append("")
        out.append("_(none recorded yet — a mechanism deliberately not adopted belongs here with its"
                   " reason, so the next conductor does not re-litigate it)_")
        out.append("")
        out.append("## Non-standard locations")
        out.append("")
        out.append("_(anything not at the default path — scripts, configs, state files)_")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def preserved_sections(path: Path) -> str:
    """Everything under headings this script does not own."""
    if not path.exists():
        return ""
    keep, cur_keep = [], False
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("## "):
            cur_keep = line[3:].strip() not in GENERATED
        elif line.startswith("# "):
            cur_keep = False
        if cur_keep:
            keep.append(line)
    return "\n".join(keep)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if the report is stale")
    args = ap.parse_args()

    rows, notes = wired_hooks()
    want = render(rows, notes, preserved_sections(OUT))
    have = OUT.read_text(encoding="utf-8") if OUT.exists() else None

    if args.check:
        if have == want:
            print(f"ok  {OUT.relative_to(REPO).as_posix()} is current")
            return 0
        print(f"STALE  {OUT.relative_to(REPO).as_posix()} — run: python tools/report-installed.py")
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(want, encoding="utf-8")
    missing = [r for r in rows if not r["exists"]]
    print(f"wrote {OUT.relative_to(REPO).as_posix()}  ({len(rows)} wired hooks, "
          f"{len(missing)} wired-but-missing)")
    for r in missing:
        print(f"  !! WIRED BUT ABSENT: {r['event']} -> {r['file']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
